version: "3.9"
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.16.4-rk
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    shm_size: "512mb"
    devices:
      - /dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/video-dec0:/dev/video-dec0
      - /dev/video-enc0:/dev/video-enc0
      - /dev/rga
      - /dev/mpp_service
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD129
    environment:
      - FRIGATE_RTSP_PASSWORD="password"
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
      - FRIGATE_JWT_SECRET=iBFcoalGWCj30UW2BzLnShsRsRF7zcnJ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971 # Port used by Web UI.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.frigate-web-redirect.redirectscheme.scheme: https
      traefik.http.services.frigate.loadbalancer.server.port: 8971
      # Web
      traefik.http.routers.frigate-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.frigate-insecure.entrypoints: web
      traefik.http.routers.frigate-insecure.service: frigate
      traefik.http.routers.frigate-insecure.middlewares: frigate-web-redirect
      # Websecure
      traefik.http.routers.frigate.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.frigate.entrypoints: websecure
      traefik.http.routers.frigate.service: frigate
      traefik.http.routers.frigate.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.frigate-local-insecure.rule: Host(`frigate.${LOCAL_DOMAIN}`)
      traefik.http.routers.frigate-local-insecure.entrypoints: web
      traefik.http.routers.frigate-local-insecure.service: frigate
      traefik.http.routers.frigate-local-insecure.middlewares: frigate-web-redirect
      # Local domain secure
      traefik.http.routers.frigate-local.rule: Host(`frigate.${LOCAL_DOMAIN}`)
      traefik.http.routers.frigate-local.entrypoints: websecure
      traefik.http.routers.frigate-local.service: frigate
      traefik.http.routers.frigate-local.tls: true
      runtipi.managed: true